import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import prisma from "@/prisma/client";

const inter = Inter({ subsets: ["latin"] });

export default function Students(props) {
  //   const [student, setStudent] = useState(props.student);
  // do dynamic things once page is loaded!
  //   console.log("DETAILS?", props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="og:title" value={props.student.name} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Link href="/">Go back</Link>
          <h1>DETAILS</h1>
          <div>
            <h2>{props.student.name}</h2>
            <p>{props.student.email}</p>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(req) {
  console.log("WHAT IS THIS?", req.params.studentId);
  // we need the id of this student

  // get this student from the database
  const student = await prisma.student.findUnique({
    where: {
      id: req.params.studentId,
    },
  });

  if (!student) {
    return { notFound: true };
  }

  // return as props
  return {
    props: { student: student },
  };
}
