import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import prisma from "@/prisma/client";

const inter = Inter({ subsets: ["latin"] });

export default function Students(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Link href="/">Go back</Link> -
          <Link href="/students/new">Add a glorious student</Link>
          <h1>Students</h1>
          <div>
            {props.students.map((student) => (
              <Link key={student.id} href={`/students/${student.id}`}>
                <p>
                  {student.name} - {student.email}
                </p>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const students = await prisma.student.findMany({ take: 20 });

  return {
    props: { students: students },
  };
}
